import os
import json

en_adds = {
  "report": {
    "title": "BeeLocate PRO - Location Suitability Report",
    "header_badge": "Location Suitability Report",
    "header_desc": "Research-based decision support for beekeeping site assessment.",
    "date": "Date:",
    "location": "Location:",
    "analysis_window": "Analysis window:",
    "download_pdf": "Download PDF",
    "unlimited_active": "Unlimited analyses are active for 24 hours.",
    "expires_in": "Expires in ",
    "until": " (until ",
    "unlock_full": "Unlock full report for {price_label}",
    "preview_hint": "Preview only. Purchase unlocks the full PDF + unlimited analyses for today.",
    "overall_suitability": "Overall Suitability",
    "why_this_score": "Why this score?",
    "high_level": "(High-level)",
    "general_interpretation": "General Interpretation",
    "ai_insights": "AI Insights",
    "premium": "(Premium)",
    "ai_forage": "Forage & Honey Potential",
    "ai_terrain": "Terrain & Placement Constraints",
    "ai_climate": "Climate & Flight Activity",
    "ai_access": "Access, Water & Human Pressure",
    "ai_best_use": "Best use case",
    "ai_next_checks": "Top 3 next checks on the ground",
    "ai_key_drivers": "Key drivers",
    "ai_risks": "Risks",
    "ai_field_checks": "Field checks",
    "preparing_ai": "Preparing expert commentary…",
    "ai_wait_hint": "This usually takes 5–20 seconds. This page will refresh automatically when ready.",
    "ai_status": "Status:",
    "ai_elapsed": "Elapsed:",
    "ai_unavailable": "AI commentary is temporarily unavailable. The rest of the report remains valid.",
    "ai_refresh_hint": "Try refreshing this page or downloading the PDF again.",
    "ai_paywall_desc": "This premium section explains *why* the score looks this way, what is limiting, and what to validate on-site.",
    "ai_paywall_b1": "• Key drivers and limiting factors",
    "ai_paywall_b2": "• Risk profile for the selected season",
    "ai_paywall_b3": "• Practical field checklist before placing hives",
    "unlock_ai": "Unlock AI insights + full PDF for {price_label}",
    "key_indicators": "Key Indicators",
    "snapshot": "(Snapshot)",
    "more_indicators_locked": "more indicators are locked in the full report.",
    "local_comparison": "Local Comparison",
    "local_baseline_hint": "Your location vs regional baseline (sampled)",
    "your_score": "Your score:",
    "regional_avg": "Regional avg:",
    "tip_conditional_yes": "If your score is above the baseline but the \"why\" points include a strong limiting factor (e.g., steep slope, low vegetation continuity), treat this as a \"conditional yes\" and validate on site.",
    "detailed_breakdown_title": "Detailed Card Breakdown",
    "detailed_breakdown_desc1": "This table lists the 14 analysis cards (value, source, and interpretation).",
    "detailed_breakdown_desc2": "most values are locked.",
    "th_card": "Card",
    "th_value": "Value",
    "th_source": "Source",
    "why_it_matters": "Why it matters:",
    "how_beelocate_uses": "How BeeLocate uses it:",
    "locked": "Locked",
    "unlock_to_view": "(unlock to view)",
    "methodology_note": "Methodology note:",
    "legal_disclaimer": "Legal disclaimer:",
    "page_1_of_1": "Page 1 of 1",
    "preview_mode_print": "Preview Mode • Optimized for A4 Printing"
  }
}

tr_adds = {
  "report": {
    "title": "BeeLocate PRO - Konum Uygunluk Raporu",
    "header_badge": "Konum Uygunluk Raporu",
    "header_desc": "Arıcılık sahası değerlendirmesi için araştırmaya dayalı karar desteği.",
    "date": "Tarih:",
    "location": "Konum:",
    "analysis_window": "Analiz dönemi:",
    "download_pdf": "PDF İndir",
    "unlimited_active": "24 saat boyunca sınırsız analiz aktif.",
    "expires_in": "Sona ermesine ",
    "until": " (bitiş ",
    "unlock_full": "{price_label} ödeyerek tam raporun kilidini açın",
    "preview_hint": "Sadece önizleme. Satın alma işlemi tam PDF'in ve bugün için sınırsız analizin kilidini açar.",
    "overall_suitability": "Genel Uygunluk",
    "why_this_score": "Neden bu puan?",
    "high_level": "(Üst düzey)",
    "general_interpretation": "Genel Yorum",
    "ai_insights": "Yapay Zeka Görüşleri",
    "premium": "(Premium)",
    "ai_forage": "Nektar ve Bal Potansiyeli",
    "ai_terrain": "Arazi ve Yerleşim Kısıtlamaları",
    "ai_climate": "İklim ve Uçuş Aktivitesi",
    "ai_access": "Erişim, Su ve İnsan Baskısı",
    "ai_best_use": "En iyi kullanım senaryosu",
    "ai_next_checks": "Sahada kontrol edilecek ilk 3 şey",
    "ai_key_drivers": "Ana Etkenler",
    "ai_risks": "Riskler",
    "ai_field_checks": "Saha Kontrolleri",
    "preparing_ai": "Uzman yorumu hazırlanıyor…",
    "ai_wait_hint": "Bu işlem genellikle 5-20 saniye sürer. Sayfa hazır olduğunda otomatik olarak yenilenecektir.",
    "ai_status": "Durum:",
    "ai_elapsed": "Geçen süre:",
    "ai_unavailable": "Yapay zeka yorumu şu anda kullanılamıyor. Raporun geri kalanı geçerliliğini koruyor.",
    "ai_refresh_hint": "Bu sayfayı yenilemeyi veya PDF'i tekrar indirmeyi deneyin.",
    "ai_paywall_desc": "Bu premium bölüm, puanın *neden* böyle olduğunu, nelerin sınırlayıcı olduğunu ve sahada nelerin doğrulanması gerektiğini açıklar.",
    "ai_paywall_b1": "• Ana etkenler ve sınırlayıcı faktörler",
    "ai_paywall_b2": "• Seçilen sezon için risk profili",
    "ai_paywall_b3": "• Kovanları yerleştirmeden önce pratik saha kontrol listesi",
    "unlock_ai": "YZ yorumları ve tam PDF'i {price_label} ile aç",
    "key_indicators": "Temel Göstergeler",
    "snapshot": "(Özet)",
    "more_indicators_locked": "kadar daha gösterge tam raporda kilitlidir.",
    "local_comparison": "Yerel Karşılaştırma",
    "local_baseline_hint": "Konumunuz ile bölgesel taban çizgisi (örneklenmiş)",
    "your_score": "Puanınız:",
    "regional_avg": "Bölgesel ortalama:",
    "tip_conditional_yes": "Puanınız ortalamanın üzerindeyse ancak \"neden\" kısmında güçlü bir sınırlayıcı unsur varsa (ör. dik eğim, düşük bitki örtüsü), bunu \"koşullu evet\" olarak değerlendirin ve sahada doğrulayın.",
    "detailed_breakdown_title": "Ayrıntılı Kart Kırılımı",
    "detailed_breakdown_desc1": "Bu tablo 14 analiz kartını (değer, kaynak ve yorum) listeler.",
    "detailed_breakdown_desc2": "çoğu değer kilitlidir.",
    "th_card": "Kart",
    "th_value": "Değer",
    "th_source": "Kaynak",
    "why_it_matters": "Neden önemli:",
    "how_beelocate_uses": "BeeLocate nasıl kullanıyor:",
    "locked": "Kilitli",
    "unlock_to_view": "(görmek için kilidi açın)",
    "methodology_note": "Metodoloji notu:",
    "legal_disclaimer": "Yasal uyarı:",
    "page_1_of_1": "Sayfa 1 / 1",
    "preview_mode_print": "Önizleme Modu • A4 Baskı İçin Optimize Edilmiştir"
  }
}

for lang, adds in [("en", en_adds), ("tr", tr_adds)]:
    path = f"/Users/alperbayrakdar/Desktop/beelocate-main-1/translations/{lang}.json"
    with open(path, "r") as f:
        data = json.load(f)
    data.update(adds)
    with open(path, "w") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

path = '/Users/alperbayrakdar/Desktop/beelocate-main-1/templates/report.html'
with open(path, 'r') as f:
    c = f.read()

repls = [
    ('<title>BeeLocate PRO - Location Suitability Report</title>', '<title>{{ t(\'report.title\') }}</title>'),
    ('>Location Suitability Report<', '>{{ t(\'report.header_badge\') }}<'),
    ('>Research-based decision support for beekeeping site assessment.<', '>{{ t(\'report.header_desc\') }}<'),
    ('>Date:<', '>{{ t(\'report.date\') }}<'),
    ('>Location:<', '>{{ t(\'report.location\') }}<'),
    ('>Analysis window:<', '>{{ t(\'report.analysis_window\') }}<'),
    ('Download PDF', '{{ t(\'report.download_pdf\') }}'),
    ('Unlimited analyses are active for 24 hours.', '{{ t(\'report.unlimited_active\') }}'),
    ('Expires in <b>', '{{ t(\'report.expires_in\') }} <b>'),
    ('<span style="opacity:.75">(until <span id="rptExpiresAt">--</span>)</span>', '<span style="opacity:.75">{{ t(\'report.until\') }}<span id="rptExpiresAt">--</span>)</span>'),
    ('Unlock full report for {{ price_label }}', '{{ t(\'report.unlock_full\', price_label=price_label) }}'),
    ('Preview only. Purchase unlocks the full PDF + unlimited analyses for today.', '{{ t(\'report.preview_hint\') }}'),
    ('>Overall Suitability<', '>{{ t(\'report.overall_suitability\') }}<'),
    ('Why this score?', '{{ t(\'report.why_this_score\') }}'),
    ('(High-level)', '{{ t(\'report.high_level\') }}'),
    ('General Interpretation', '{{ t(\'report.general_interpretation\') }}'),
    ('AI Insights', '{{ t(\'report.ai_insights\') }}'),
    ('(Premium)', '{{ t(\'report.premium\') }}'),
    ('>Forage & Honey Potential<', '>{{ t(\'report.ai_forage\') }}<'),
    ('>Terrain & Placement Constraints<', '>{{ t(\'report.ai_terrain\') }}<'),
    ('>Climate & Flight Activity<', '>{{ t(\'report.ai_climate\') }}<'),
    ('>Access, Water & Human Pressure<', '>{{ t(\'report.ai_access\') }}<'),
    ('>Best use case<', '>{{ t(\'report.ai_best_use\') }}<'),
    ('>Top 3 next checks on the ground<', '>{{ t(\'report.ai_next_checks\') }}<'),
    ('>Key drivers<', '>{{ t(\'report.ai_key_drivers\') }}<'),
    ('>Risks<', '>{{ t(\'report.ai_risks\') }}<'),
    ('>Field checks<', '>{{ t(\'report.ai_field_checks\') }}<'),
    ('Preparing expert commentary…', '{{ t(\'report.preparing_ai\') }}'),
    ('This usually takes 5–20 seconds. This page will refresh automatically when ready.', '{{ t(\'report.ai_wait_hint\') }}'),
    ('Status: <span', '{{ t(\'report.ai_status\') }} <span'),
    ('Elapsed: <span', '{{ t(\'report.ai_elapsed\') }} <span'),
    ('AI commentary is temporarily unavailable. The rest of the report remains valid.', '{{ t(\'report.ai_unavailable\') }}'),
    ('Try refreshing this page or downloading the PDF again.', '{{ t(\'report.ai_refresh_hint\') }}'),
    ('This premium section explains *why* the score looks this way, what is limiting, and what to validate on-site.', '{{ t(\'report.ai_paywall_desc\') }}'),
    ('• Key drivers and limiting factors', '{{ t(\'report.ai_paywall_b1\') }}'),
    ('• Risk profile for the selected season', '{{ t(\'report.ai_paywall_b2\') }}'),
    ('• Practical field checklist before placing hives', '{{ t(\'report.ai_paywall_b3\') }}'),
    ('Unlock AI insights + full PDF for {{ price_label }}', '{{ t(\'report.unlock_ai\', price_label=price_label) }}'),
    ('>Key Indicators <', '>{{ t(\'report.key_indicators\') }} <'),
    ('(Snapshot)', '{{ t(\'report.snapshot\') }}'),
    ('more indicators are locked in the full report.', '{{ t(\'report.more_indicators_locked\') }}'),
    ('>Local Comparison<', '>{{ t(\'report.local_comparison\') }}<'),
    ('Your location vs regional baseline (sampled)', '{{ t(\'report.local_baseline_hint\') }}'),
    ('Your score:', '{{ t(\'report.your_score\') }}'),
    ('Regional avg:', '{{ t(\'report.regional_avg\') }}'),
    ('<strong>Tip:</strong> If your score is above the baseline but the "why" points include a strong limiting factor (e.g., steep slope, low vegetation continuity), treat this as a "conditional yes" and validate on site.', '<strong>Tip:</strong> {{ t(\'report.tip_conditional_yes\') }}'),
    ('>Detailed Card Breakdown<', '>{{ t(\'report.detailed_breakdown_title\') }}<'),
    ('This table lists the 14 analysis cards (value, source, and interpretation).', '{{ t(\'report.detailed_breakdown_desc1\') }}'),
    ('<strong>Preview mode:</strong> most values are locked.', '<strong>Preview mode:</strong> {{ t(\'report.detailed_breakdown_desc2\') }}'),
    ('>Card<', '>{{ t(\'report.th_card\') }}<'),
    ('>Value<', '>{{ t(\'report.th_value\') }}<'),
    ('>Source<', '>{{ t(\'report.th_source\') }}<'),
    ('>Why it matters:<', '>{{ t(\'report.why_it_matters\') }}<'),
    ('>How BeeLocate uses it:<', '>{{ t(\'report.how_beelocate_uses\') }}<'),
    ('>Locked<', '>{{ t(\'report.locked\') }}<'),
    ('(unlock to view)', '{{ t(\'report.unlock_to_view\') }}'),
    ('Methodology note:', '{{ t(\'report.methodology_note\') }}'),
    ('Legal disclaimer:', '{{ t(\'report.legal_disclaimer\') }}'),
    ('>Page 1 of 1<', '>{{ t(\'report.page_1_of_1\') }}<'),
    ('Preview Mode • Optimized for A4 Printing', '{{ t(\'report.preview_mode_print\') }}')
]

for o, n in repls:
    c = c.replace(o, n)

with open(path, 'w') as f:
    f.write(c)

print('Done')
